<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width-content-width, initial-scale=1.0">
	<title>Disney+ | O melhor da Disney só para ti</title>
	<link rel="stylesheet" href="/css/style_login.css">
	<link rel="shortcut icon" href="/imagens/disney-plus-logo.svg" type="image/x-icon">
</head>

<body style="background: url('../imagens/login.jpeg'); background-repeat: no-repeat center center fixed;background-size: cover;" >
	<a class="btn-login" href="/login">Login</a>
	<div class="hero-content-login">
	<img class="logo-login" src="/imagens/logo.png" alt="Disney+">
	<h1>As melhores histórias, <br> 
	num único lugar.</h1>
	<div class="prices-container">
		<div class="prices">
			<div>
			<p><span>9,90€</span> /mês*</p>
			<p>Sem fidelização. Subscrição necessária.</p>
			</div>
			<a href="#">Teste Gratuito</a>
		</div>
		<div class="prices">
			<p><span>99,90€</span> /ano*</p>
			<p>Poupança equivalente a 2 meses. Aplicam-se termos e condições.</p>
			<a href="#">Subscreve Já</a>
		</div>
	</div>
</body>

</html>