
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  
  <link rel="stylesheet" href="/css/style_registo.css">
  <link rel="shortcut icon" href="/imagens/disney-plus-logo.svg" type="image/x-icon">
  <title>Inscrição</title>
</head>
<body>
<div class="container">
  <div class="d-flex justify-content-center mt-5">
    <div class="card" style="width: 36rem;">
      <div class="card-body">

        <div class="d-flex justify-content-center">
          <img src="/imagens/disney.PNG" />
        </div>

        <div class="row">
          <div class="col">
            <h2>Cria a tua conta</h2>
          </div>
        </div>

        <div class="row">
          <div class="col">
            
            <form action="/registrar" method="post">
              <div class="form-group">
                <input type="text" value="<?= $this->view->utilizador['nome'] ?>" name="nome" class="form-control" placeholder="Nome" >
              </div>
              
              <div class="form-group">
                <input type="text" value="<?= $this->view->utilizador['email'] ?>" name="email" class="form-control" placeholder="E-mail">
              </div>

              <div class="form-group">
                <input type="password" value="<?= $this->view->utilizador['senha'] ?>" name="senha" class="form-control" placeholder="Senha" >
              </div>
              <br>
             
              <button type="submit" class="btn btn-primary btn-block">Inscrever-se</button>
              <?php if($this->view->erroinscricao) { ?>

                <small class="form-text text-danger">*Erro ao tentar realizar a inscrição, verifica se os campos foram preenchidos corretamente.</small>

              <?php } ?>
            </form>

          </div>
        </div>

      </div>
    </div>
  </div>
</div>
</body>
</html>

