<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="/css/style_registo.css">
  <link rel="shortcut icon" href="/imagens/disney-plus-logo.svg" type="image/x-icon">
  <title>Inscrição</title>
</head>
<body>
<div class="container">
  <div class="d-flex justify-content-center mt-5">
    <div class="card" style="width: 36rem;">
      <div class="card-body">

        <div class="d-flex justify-content-center">
          <img src="/imagens/disney.PNG" />
        </div>

        <div class="row">
          <div class="col">
            <h2>Inscrição realizada com sucesso!</h2>
          </div>
        </div>

        <div class="row">
          <div class="col">
            <a href="/login" class="btn btn-primary btn-block">Clique aqui para fazer login!</a>
          </div>
        </div>

      </div>
    </div>
  </div>
</div>
</body>
</html>






    
  