<html lang="en">

<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">

	<title>Disney+ Clone</title>
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" 
	integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" 
	integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
	<link rel="stylesheet" href="/css/style_disney.css">
	<link rel="shortcut icon" href="/imagens/disney-plus-logo.svg" type="image/x-icon">
	
</head>

<body>

	<nav class="navbar">
		<img src="imagens/logo.png" class="brand-logo" alt="">
		<ul class="nav-links">
			<li class="nav-items"><a href="#home">Home</a></li>
			<li class="nav-items"><a href="#filmes">Filmes</a></li>
			<li class="nav-items"><a href="#series">Séries</a></li>
			<li class="nav-items"><a href="#subscricao">Subscrever</a></li>
		</ul>

		<div class="right-container">
			<input type="text" class="search-box" placeholder="procurar aqui">
			<button class="sub-btn">Confirmar</button>
			<a href="/sair" class="login-link">Terminar sessão</a>
		</div>
	</nav>

	<div class="carousel-container">
		<div class="carousel">
			<div class="slider">
				<div class="slide-content">
					<h1 class="movie-title">WandaVision</h1>
					<p class="movie-des">Combinação do estilo clássico dos sitcons 
					com o universo cinematográfico da Marvel, a série coloca os 
					super-heróis Wanda Maximoff e Vision num idílico cenário suburbano 
					dosanos 50 quando começam a suspeitar que nem tudo é o que parece.</p>
				</div>
				<img src="imagens/banner1.jpg" alt="">
			</div>
			<div class="slider">
				<div class="slide-content">
					<h1 class="movie-title">Falcão e o Soldado do Inverno</h1>
					<p class="movie-des">Falcão e o Soldado do Inverno são obrigados a 
						formar uma dupla incompatível e embarcarem em uma aventura global 
						que deve testar tanto as suas habilidades de sobrevivência quanto 
						a sua paciência.</p>
				</div>
				<img src="imagens/banner2.jpg" alt="">
			</div>
			<div class="slider">
				<div class="slide-content">
					<h1 class="movie-title">Loki</h1>
					<p class="movie-des">Loki é uma série original que se passa após os eventos
					narrados em Vingadores: Endgame. O spin-off segue os passos de Loki, 
					mais conhecido como Deus da Mentira, que conseguiu roubar o Tesseract 
					dos Vingadores durante a missão de recuperar as Jóias do Infinito.</p>
				</div>
				<img src="imagens/banner3.jfif" alt="">
			</div>
			<div class="slider">
				<div class="slide-content">
					<h1 class="movie-title">E Se…?</h1>
					<p class="movie-des">E Se…? é uma série de animação que leva o público para 
					um terreno desconhecido ao contar, de forma alternativa, momentos cruciais 
					do Universo Cinematográfico da Marvel, imaginando o que teria acontecido 
					aos super-heróis se a história fosse totalmente diferente e se passasse
					em outra realidade.</p>
				</div>
				<img src="imagens/banner4.jpeg" alt="">
			</div>
			<div class="slider">
				<div class="slide-content">
					<h1 class="movie-title">Viúva Negra</h1>
					<p class="movie-des">No thriller de espionagem repleto de ação "Viúva Negra", 
					da Marvel Studios, Natasha Romanoff, também conhecida como Viúva Negra, 
					enfrenta o lado mais sombrio da sua vida, quando surge uma perigosa 
					conspiração ligada ao seu passado. Perseguida por uma força que tudo 
					fará para a derrotar, Natasha tem de lidar com o seu historial 
					enquanto espia e com as relações desfeitas que deixou pelo caminho, 
					muito antes de se tornar uma Vingadora.</p>
				</div>
				<img src="imagens/banner5.jpg" alt="">
			</div>
			<div class="slider">
				<div class="slide-content">
					<h1 class="movie-title">Homem-Aranha: Sem Volta a Casa</h1>
					<p class="movie-des">O Homem-Aranha precisa lidar com as consequências 
					da sua verdadeira identidade ter sido descoberta. Em breve, dia
					17 de Dezembro de 2021 nos cinemas. Pré-venda vai ser dada apenas nos cinemas 
					selecionados (IMAX ou 4DX), dia 15 de Dezembro de 2021. Filme só estará 
					disponível no Disney+ um mês depois da sua estreia em cinemas nacionais.</p>
				</div>
				<img src="imagens/banner6.jpg" alt="">
				</div>
				<div class="slider">
				<div class="slide-content">
					<h1 class="movie-title">O Mandaloriano: Temporada 2</h1>
					<p class="movie-des">O Mandaloriano foi encarregado de devolver a sua carga, 
					uma criança, ao seu povo, os Jedi. Ele começa a procurar por outros 
					Mandalorianos que ele acredita que podem ajudá-lo a encontrar os Jedi
					e é direcionado a um suposto Mandaloriano que opera na cidade de Mos Pelgo, 
					em Tatooine.</p>
				</div>
				<img src="imagens/banner7.jpeg" alt="">
			</div>
			<script>
			var myIndex = 0;
			ciclo();

			function ciclo() {
			var i;
			var x = document.getElementsByClassName("slider");
			for (i = 0; i < x.length; i++) {
				x[i].style.display = "none";  
			}
			myIndex++;
			if (myIndex > x.length) {myIndex = 1}    
			x[myIndex-1].style.display = "block";  
			setTimeout(ciclo, 3000); // muda imagem a cada 3 segundos
			}
			</script>
		</div>
	</div>
	
	<div class="video-card-container">
		<div class="video-card">
			<img src="imagens/disney.PNG" class="video-card-image" alt="">
			<video src="videos/disney.mp4" mute loop class="card-video"></video>
		</div>
		<div class="video-card">
			<img src="imagens/pixar.PNG" class="video-card-image" alt="">
			<video src="videos/pixar.mp4" mute loop class="card-video"></video>
		</div>
		<div class="video-card">
			<img src="imagens/marvel.PNG" class="video-card-image" alt="">
			<video src="videos/marvel.mp4" mute loop class="card-video"></video>
		</div>
		<div class="video-card">
			<img src="imagens/star-wars.PNG" class="video-card-image" alt="">
			<video src="videos/star-war.mp4" mute loop class="card-video"></video>
		</div>
		<div class="video-card">
			<img src="imagens/geographic.PNG" class="video-card-image" alt="">
			<video src="videos/geographic.mp4" mute loop class="card-video"></video>
		</div>
	</div>

	<h1 class="title">Recomendado Para Ti</h1>
	<div class="movies-list">
		<button class="pre-btn"><img src="imagens/pre.png" alt=""></button>
		<button class="nxt-btn"><img src="imagens/nxt.png" alt=""></button>
		<div class="card-container">
			<div class="card">
				<img src="imagens/recomendado1.png" class="card-img" alt="">
				<div class="card-body">
					<h2 class="name">WandaVision</h2>
				<a href="https://www.youtube.com/watch?v=sj9J2ecsSpo" target="_blank" rel="noopener noreferrer"><h6 class="des">Ver Trailer</h6></a>
					<button class="watchlist-btn">Adicionar a lista</button>
				</div>
			</div>
			<div class="card">
				<img src="imagens/recomendado2.jpg" class="card-img" alt="">
				<div class="card-body">
					<h2 class="name">Gavião-Arqueiro</h2>
			<a href="https://www.youtube.com/watch?v=5VYb3B1ETlk" target="_blank" rel="noopener noreferrer"><h6 class="des">Ver Trailer</h6></a>
					<button class="watchlist-btn">Adicionar a lista</button>
				</div>
			</div>
			<div class="card">
				<img src="imagens/recomendado3.jpeg" class="card-img" alt="">
				<div class="card-body">
					<h2 class="name">Shang-Chi e a Lenda dos 10 Anéis</h2>
				<a href="https://www.youtube.com/watch?v=8YjFbMbfXaQ&t=1s" target="_blank" rel="noopener noreferrer"><h6 class="des">Ver Trailer</h6></a>
					<button class="watchlist-btn">Adicionar a lista</button>
				</div>
			</div>
			<div class="card">
				<img src="imagens/recomendado4.jpg" class="card-img" alt="">
				<div class="card-body">
					<h2 class="name">Eternos</h2>
					<a href="https://www.youtube.com/watch?v=x_me3xsvDgk" target="_blank" rel="noopener noreferrer"><h6 class="des">Ver Trailer</h6></a>
					<button class="watchlist-btn">Adicionar a lista</button>
				</div>
			</div>
			<div class="card">
				<img src="imagens/recomendado5.jfif" class="card-img" alt="">
				<div class="card-body">
					<h2 class="name">Mulan</h2>
					<a href="https://www.youtube.com/watch?v=KK8FHdFluOQ" target="_blank" rel="noopener noreferrer"><h6 class="des">Ver Trailer</h6></a>
					<button class="watchlist-btn">Adicionar a lista</button>
				</div>
			</div>
			<div class="card">
				<img src="imagens/recomendado6.jpg" class="card-img" alt="">
				<div class="card-body">
					<h2 class="name">Soul, um Filme com Alma</h2>
					<a href="https://www.youtube.com/watch?v=xOsLIiBStEs" target="_blank" rel="noopener noreferrer"><h6 class="des">Ver Trailer</h6></a>
					<button class="watchlist-btn">Adicionar a lista</button>
				</div>
			</div>
			<div class="card">
				<img src="imagens/recomendado7.jpg" class="card-img" alt="">
				<div class="card-body">
					<h2 class="name">Raya e o Último Dragão</h2>
					<a href="https://www.youtube.com/watch?v=1VIZ89FEjYI" target="_blank" rel="noopener noreferrer"><h6 class="des">Ver Trailer</h6></a>
					<button class="watchlist-btn">Adicionar a lista</button>
				</div>
			</div>
			<div class="card">
				<img src="imagens/recomendado8.jpg" class="card-img" alt="">
				<div class="card-body">
					<h2 class="name">O Mandaloriano (Temporada 1)</h2>
					<a href="https://www.youtube.com/watch?v=aOC8E8z_ifw" target="_blank" rel="noopener noreferrer"><h6 class="des">Ver Trailer</h6></a>
					<button class="watchlist-btn">Adicionar a lista</button>
				</div>
			</div>
			<div class="card">
				<img src="imagens/recomendado9.jpg" class="card-img" alt="">
				<div class="card-body">
					<h2 class="name">O Livro de Boba Fett</h2>
					<a href="https://www.youtube.com/watch?v=rOJ1cw6mohw" target="_blank" rel="noopener noreferrer"><h6 class="des">Ver Trailer</h6></a>
					<h6 class="des">Muito brevemente, a 29 Dez 2021</h6>
				</div>
			</div>
			<div class="card">
				<img src="imagens/recomendado10.jpg" class="card-img" alt="">
				<div class="card-body">
					<h2 class="name">Toy Story 4</h2>
					<a href="https://www.youtube.com/watch?v=wmiIUN-7qhE" target="_blank" rel="noopener noreferrer"><h6 class="des">Ver Trailer</h6></a>
					<button class="watchlist-btn">Adicionar a lista</button>
				</div>
			</div>
			<div class="card">
				<img src="imagens/recomendado11.jpg" class="card-img" alt="">
				<div class="card-body">
					<h2 class="name">Homem-Aranha: Sem Volta a Casa</h2>
					<a href="https://www.youtube.com/watch?v=JfVOs4VSpmA" target="_blank" rel="noopener noreferrer"><h6 class="des">Ver Trailer</h6></a>
					<button class="watchlist-btn">Adicionar a lista</button>
				</div>
			</div>
			<div class="card">
				<img src="imagens/recomendado12.jpg" class="card-img" alt="">
				<div class="card-body">
					<h2 class="name">O Mandaloriano (Temporada 2)</h2>
					<a href="https://www.youtube.com/watch?v=eW7Twd85m2g&t=4s" target="_blank" rel="noopener noreferrer"><h6 class="des">Ver Trailer</h6></a>
					<button class="watchlist-btn">Adicionar a lista</button>
				</div>
			</div>
			<div class="card">
				<img src="imagens/recomendado13.jpg" class="card-img" alt="">
				<div class="card-body">
					<h2 class="name">Rogue One: Um filme de Star Wars</h2>
					<a href="https://www.youtube.com/watch?v=frdj1zb9sMY" target="_blank" rel="noopener noreferrer"><h6 class="des">Ver Trailer</h6></a>
					<button class="watchlist-btn">Adicionar a lista</button>
				</div>
			</div>
			<div class="card">
				<img src="imagens/recomendado14.jpg" class="card-img" alt="">
				<div class="card-body">
					<h2 class="name">Os Incriveis</h2>
					<a href="https://www.youtube.com/watch?v=-UaGUdNJdRQ" target="_blank" rel="noopener noreferrer"><h6 class="des">Ver Trailer</h6></a>
					<button class="watchlist-btn">Adicionar a lista</button>
				</div>
			</div>
			<div class="card">
				<img src="imagens/recomendado16.png" class="card-img" alt="">
				<div class="card-body">
					<h2 class="name">Solo: Um filme de Star Wars</h2>
					<a href="https://www.youtube.com/watch?v=jPEYpryMp2s" target="_blank" rel="noopener noreferrer"><h6 class="des">Ver Trailer</h6></a>
					<button class="watchlist-btn">Adicionar a lista</button>
				</div>
			</div>
			<div class="card">
				<img src="imagens/recomendado15.png" class="card-img" alt="">
				<div class="card-body">
					<h2 class="name">Os Incriveis 2</h2>
					<a href="https://www.youtube.com/watch?v=i5qOzqD9Rms" target="_blank" rel="noopener noreferrer"><h6 class="des">Ver Trailer</h6></a>
					<button class="watchlist-btn">Adicionar a lista</button>
				</div>
			</div>
			<div class="card">
				<img src="imagens/recomendado17.jpg" class="card-img" alt="">
				<div class="card-body">
					<h2 class="name">Os Simpsons</h2>
					<a href="https://www.youtube.com/watch?v=_UlD0AbDYGU" target="_blank" rel="noopener noreferrer"><h6 class="des">Ver Trailer</h6></a>
					<button class="watchlist-btn">Adicionar a lista</button>
				</div>
			</div>
		</div>
		<h1 class="title">Os Clássicos</h1>
		<div class="movies-list">
			<button class="pre-btn"><img src="imagens/pre.png" alt=""></button>
			<button class="nxt-btn"><img src="imagens/nxt.png" alt=""></button>
			<div class="card-container">
				<div class="card">
					<img src="imagens/classicos1.jpeg" class="card-img" alt="">
					<div class="card-body">
						<h2 class="name">Lilo & Stitch</h2>
						<a href="https://www.youtube.com/watch?v=9OAC55UWAQs" target="_blank" rel="noopener noreferrer"><h6 class="des">Ver Trailer</h6></a>>
						<button class="watchlist-btn">Adicionar a lista</button>
					</div>
				</div>
				<div class="card">
					<img src="imagens/classicos2.jpg" class="card-img" alt="">
					<div class="card-body">
						<h2 class="name">101 Dálmatas</h2>
						<a href="https://www.youtube.com/watch?v=VApVpvcGW1A" target="_blank" rel="noopener noreferrer"><h6 class="des">Ver Trailer</h6></a>
						<button class="watchlist-btn">Adicionar a lista</button>
					</div>
				</div>
				<div class="card">
					<img src="imagens/classicos3.jpg" class="card-img" alt="">
					<div class="card-body">
						<h2 class="name">Peter Pan na Terra do Nunca</h2>
						<a href="https://www.youtube.com/watch?v=L-o0ufCPANo" target="_blank" rel="noopener noreferrer"><h6 class="des">Ver Trailer</h6></a>
						<button class="watchlist-btn">Adicionar a lista</button>
					</div>
				</div>
				<div class="card">
					<img src="imagens/classicos4.jpeg" class="card-img" alt="">
					<div class="card-body">
						<h2 class="name">Pinóquio</h2>
						<a href="https://www.youtube.com/watch?v=GBgyVY_ClzQ" target="_blank" rel="noopener noreferrer"><h6 class="des">Ver Trailer</h6></a>
						<button class="watchlist-btn">Adicionar a lista</button>
					</div>
				</div>
				<div class="card">
					<img src="imagens/classicos5.jpg" class="card-img" alt="">
					<div class="card-body">
						<h2 class="name">Branca de Neve e os 7 Anões</h2>
						<a href="https://www.youtube.com/watch?v=5fzZFQBXSLM" target="_blank" rel="noopener noreferrer"><h6 class="des">Ver Trailer</h6></a>
						<button class="watchlist-btn">Adicionar a lista</button>
					</div>
				</div>
				<div class="card">
					<img src="imagens/classicos6.jpg" class="card-img" alt="">
					<div class="card-body">
						<h2 class="name">Aladdin</h2>
						<a href="https://www.youtube.com/watch?v=eTjHiQKJUDY" target="_blank" rel="noopener noreferrer"><h6 class="des">Ver Trailer</h6></a>
						<button class="watchlist-btn">Adicionar a lista</button>
					</div>
				</div>
				<div class="card">
					<img src="imagens/classicos7.jpeg" class="card-img" alt="">
					<div class="card-body">
						<h2 class="name">Dumbo</h2>
						<a href="https://www.youtube.com/watch?v=tLtQ3bCvBA0" target="_blank" rel="noopener noreferrer"><h6 class="des">Ver Trailer</h6></a>
						<button class="watchlist-btn">Adicionar a lista</button>
					</div>
				</div>
				<div class="card">
					<img src="imagens/classicos8.jpg" class="card-img" alt="">
					<div class="card-body">
						<h2 class="name">Alice no País das Maravilhas</h2>
						<a href="https://www.youtube.com/watch?v=PA-h3-0wheo" target="_blank" rel="noopener noreferrer"><h6 class="des">Ver Trailer</h6></a>
						<button class="watchlist-btn">Adicionar a lista</button>
					</div>
				</div>
				<div class="card">
					<img src="imagens/classicos9.jpg" class="card-img" alt="">
					<div class="card-body">
						<h2 class="name">O Rei Leão</h2>
						<a href="https://www.youtube.com/watch?v=lFzVJEksoDY" target="_blank" rel="noopener noreferrer"><h6 class="des">Ver Trailer</h6></a>
						<button class="watchlist-btn">Adicionar a lista</button>
					</div>
				</div>
				<div class="card">
					<img src="imagens/classicos10.jpg" class="card-img" alt="">
					<div class="card-body">
						<h2 class="name">Hércules</h2>
						<a href="https://www.youtube.com/watch?v=vlblxDGoGwo" target="_blank" rel="noopener noreferrer"><h6 class="des">Ver Trailer</h6></a>
						<button class="watchlist-btn">Adicionar a lista</button>
					</div>
				</div>
				<div class="card">
					<img src="imagens/classicos11.jpg" class="card-img" alt="">
					<div class="card-body">
						<h2 class="name">Tarzan</h2>
						<a href="https://www.youtube.com/watch?v=ie53R2HEZ6g" target="_blank" rel="noopener noreferrer"><h6 class="des">Ver Trailer</h6></a>
						<button class="watchlist-btn">Adicionar a lista</button>
					</div>
				</div>
				<div class="card">
					<img src="imagens/classicos12.jpg" class="card-img" alt="">
					<div class="card-body">
						<h2 class="name">Star Wars: Episódio 1</h2>
						<a href="https://www.youtube.com/watch?v=bD7bpG-zDJQ" target="_blank" rel="noopener noreferrer"><h6 class="des">Ver Trailer</h6></a>
						<button class="watchlist-btn">Adicionar a lista</button>
					</div>
				</div>
				<div class="card">
					<img src="imagens/classicos13.jpg" class="card-img" alt="">
					<div class="card-body">
						<h2 class="name">Star Wars: Episódio 2</h2>
						<a href="https://www.youtube.com/watch?v=gYbW1F_c9eM" target="_blank" rel="noopener noreferrer"><h6 class="des">Ver Trailer</h6></a>
						<button class="watchlist-btn">Adicionar a lista</button>
					</div>
				</div>
				<div class="card">
					<img src="imagens/classicos14.jpg" class="card-img" alt="">
					<div class="card-body">
						<h2 class="name">Star Wars: Episódio 3</h2>
						<a href="https://www.youtube.com/watch?v=5UnjrG_N8hU" target="_blank" rel="noopener noreferrer"><h6 class="des">Ver Trailer</h6></a>
						<button class="watchlist-btn">Adicionar a lista</button>
					</div>
				</div>
				<div class="card">
					<img src="imagens/classicos15.jpg" class="card-img" alt="">
					<div class="card-body">
						<h2 class="name">Star Wars: Episódio 4</h2>
						<a href="https://www.youtube.com/watch?v=vZ734NWnAHA" target="_blank" rel="noopener noreferrer"><h6 class="des">Ver Trailer</h6></a>
						<button class="watchlist-btn">Adicionar a lista</button>
					</div>
				</div>
				<div class="card">
					<img src="imagens/classicos16.jpg" class="card-img" alt="">
					<div class="card-body">
						<h2 class="name">Star Wars: Episódio 5</h2>
						<a href="https://www.youtube.com/watch?v=JNwNXF9Y6kY" target="_blank" rel="noopener noreferrer"><h6 class="des">Ver Trailer</h6></a>
						<button class="watchlist-btn">Adicionar a lista</button>
					</div>
				</div>
				<div class="card">
					<img src="imagens/classicos17.jpg" class="card-img" alt="">
					<div class="card-body">
						<h2 class="name">Star Wars: Episódio 6</h2>
						<a href="https://www.youtube.com/watch?v=7L8p7_SLzvU" target="_blank" rel="noopener noreferrer"><h6 class="des">Ver Trailer</h6></a>
						<button class="watchlist-btn">Adicionar a lista</button>
					</div>
				</div>
			</div>
			<h1 class="title">Brevemente</h1>
			<div class="movies-list">
				<button class="pre-btn"><img src="imagens/pre.png" alt=""></button>
				<button class="nxt-btn"><img src="imagens/nxt.png" alt=""></button>
				<div class="card-container">
					<div class="card">
						<img src="imagens/breve1.jpg" class="card-img" alt="">
						<div class="card-body">
							<h2 class="name">Invasão Secreta</h2>
							<h6 class="des">Sem Informações de Momento</h6>
							<p class="des">Em Breve</p>
						</div>
					</div>
					<div class="card">
						<img src="imagens/breve2.jpg" class="card-img" alt="">
						<div class="card-body">
							<h2 class="name">Mulher-Hulk</h2>
							<h6 class="des">Sem Informações de Momento</h6>
							<p class="des">Em Breve</p>
						</div>
					</div>
					<div class="card">
						<img src="imagens/breve3.jpeg" class="card-img" alt="">
						<div class="card-body">
							<h2 class="name">Cavaleiro da Lua</h2>
							<h6 class="des">Sem Informações de Momento</h6>
							<p class="des">Em Breve</p>
						</div>
					</div>
					<div class="card">
						<img src="imagens/breve4.jpg" class="card-img" alt="">
						<div class="card-body">
							<h2 class="name">Thor: Amor e Trovão</h2>
							<h6 class="des">Sem Informações de Momento</h6>
							<p class="des">Em Breve</p>
						</div>
					</div>
					<div class="card">
						<img src="imagens/breve5.jpg" class="card-img" alt="">
						<div class="card-body">
							<h2 class="name">Pantera Negra: Wakanda Para Sempre</h2>
							<h6 class="des">Sem Informações de Momento</h6>
							<p class="des">Em Breve</p>
						</div>
					</div>
					<div class="card">
						<img src="imagens/breve6.jpg" class="card-img" alt="">
						<div class="card-body">
							<h2 class="name">Guardiões da Galáxia 3</h2>
							<h6 class="des">Sem Informações de Momento</h6>
							<p class="des">Em Breve</p>
						</div>
					</div>
					<div class="card">
						<img src="imagens/breve7.jpg" class="card-img" alt="">
						<div class="card-body">
							<h2 class="name">Encanto</h2>
							<h6 class="des">Sem Informações de Momento</h6>
							<p class="des">Em Breve</p>
						</div>
					</div>
					<div class="card">
						<img src="imagens/breve8.jpg" class="card-img" alt="">
						<div class="card-body">
							<h2 class="name">Estranhamente Vermelho</h2>
							<h6 class="des">Sem Informações de Momento</h6>
							<p class="des">Em Breve</p>
						</div>
					</div>
					<div class="card">
						<img src="imagens/breve9.jpg" class="card-img" alt="">
						<div class="card-body">
							<h2 class="name">Big Hero 6: A Série</h2>
							<h6 class="des">Sem Informações de Momento</h6>
							<p class="des">Em Breve</p>
						</div>
					</div>
					<div class="card">
						<img src="imagens/breve10.jpg" class="card-img" alt="">
						<div class="card-body">
							<h2 class="name">Star Wars: Esquadrão Desonesto</h2>
							<h6 class="des">Sem Informações de Momento</h6>
							<p class="des">Em Breve</p>
						</div>
					</div>
					<div class="card">
						<img src="imagens/breve11.jpg" class="card-img" alt="">
						<div class="card-body">
							<h2 class="name">Echo</h2>
							<h6 class="des">Sem Informações de Momento</h6>
							<p class="des">Em Breve</p>
						</div>
					</div> //
					<div class="card">
						<img src="imagens/breve12.jpg" class="card-img" alt="">
						<div class="card-body">
							<h2 class="name">Star Wars: Obi-Wan Kenobi</h2>
							<h6 class="des">Sem Informações de Momento</h6>
							<p class="des">Em Breve</p>
						</div>
					</div>
					<div class="card">
						<img src="imagens/breve13.jpg" class="card-img" alt="">
						<div class="card-body">
							<h2 class="name">Star Wars: Uma Historia de Droides</h2>
							<h6 class="des">Sem Informações de Momento</h6>
							<p class="des">Em Breve</p>
						</div>
					</div>
					<div class="card">
						<img src="imagens/breve14.jpg" class="card-img" alt="">
						<div class="card-body">
							<h2 class="name">Guerra das Armaduras</h2>
							<h6 class="des">Sem Informações de Momento</h6>
							<p class="des">Em Breve</p>
						</div>
					</div>
					<div class="card">
						<img src="imagens/breve15.jpg" class="card-img" alt="">
						<div class="card-body">
							<h2 class="name">Homem-Formiga e Vespa: Quantumania</h2>
							<h6 class="des">Sem Informações de Momento</h6>
							<p class="des">Em Breve</p>
						</div>
					</div>
					<div class="card">
						<img src="imagens/breve16.jpg" class="card-img" alt="">
						<div class="card-body">
							<h2 class="name">Desencantada</h2>
							<h6 class="des">Sem Informações de Momento</h6>
							<p class="des">Em Breve</p>
						</div>
					</div>
					<div class="card">
						<img src="imagens/breve17.jpg" class="card-img" alt="">
						<div class="card-body">
							<h2 class="name">Peter Pan E Wendy</h2>
							<h6 class="des">Sem Informações de Momento</h6>
							<p class="des">Em Breve</p>
						</div>
					</div>
					<div class="card">
						<img src="imagens/breve18.jpg" class="card-img" alt="">
						<div class="card-body">
							<h2 class="name">Zootopia+</h2>
							<h6 class="des">Sem Informações de Momento</h6>
							<p class="des">Em Breve</p>
						</div>
					</div>
					<div class="card">
						<img src="imagens/breve19.png" class="card-img" alt="">
						<div class="card-body">
							<h2 class="name">Moana: A Serie</h2>
							<h6 class="des">Sem Informações de Momento</h6>
							<p class="des">Em Breve</p>
						</div>
					</div>
					<div class="card">
						<img src="imagens/breve20.jpg" class="card-img" alt="">
						<div class="card-body">
							<h2 class="name">Star Wars: Andor</h2>
							<h6 class="des">Sem Informações de Momento</h6>
							<p class="des">Em Breve</p>
						</div>
					</div>
					<div class="card">
						<img src="imagens/breve21.jpg" class="card-img" alt="">
						<div class="card-body">
							<h2 class="name">Star Wars: Rangers da Nova Republica</h2>
							<h6 class="des">Sem Informações de Momento</h6>
							<p class="des">Em Breve</p>
						</div>
					</div>
					<div class="card">
						<img src="imagens/breve22.jpg" class="card-img" alt="">
						<div class="card-body">
							<h2 class="name">Star Wars: O Ecolyte</h2>
							<h6 class="des">Sem Informações de Momento</h6>
							<p class="des">Em Breve</p>
						</div>
					</div>
				</div>

	<!--<script src="/js/data.js"></script> --> 
	<script src="/js/app.js"></script>

<style>
	footer {
		text-align: center;
		padding: 5px;
		background-color: #0c111b;
		color: white;
	}
</style>

<footer>
	<br>
	<p>
		2021 <a href="https://www.disney.pt/todas-as-novidades-do-disney-plus"><img src="imagens/logo.PNG" alt="" width="50" height="50"></a> Todos os direitos
		reservados.
	</p>
</footer>
</body>
</html>